version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.4.10
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:3.2.3
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
##    volumes:
##      - ./logs:/logs
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka
